Error if any invalid keys are defined with `workspace = true` for `ca…
Muscraft/cargo pull request #2
Opened 2022-04-25 22:36 UTC by Muscraft

Tracking issue: #8415
RFC: rust-lang/rfcs#2906

PRs in this RFC:
- Base Implementation
  - #10497
  - #10517 
  - #10538 
  - #10548 
- New Fields 
  - #10563
  - #10565 
- Update inheritance source 
  - #10564
- Optimizations
  - #10568 
- Documentation changes
  - #10584
- `cargo-add` support
  - #10585
  - #1

Changes:
- Moved `table.get("workspace")` to the top of setting a source in `from_toml`
  - This was done so that we do not encounter keys that conflict with `workspace` before it
- Added a list of keys that conflict with `workspace = true`
- Added checking if there are any conflict keys defined when `workspace = true`

Remaining implementation work for the RFC
- `cargo-add` support, see [epage's comment](https://github.com/rust-lang/cargo/issues/8415#issuecomment-1075544790)
- Optimizations as needed

r? @epage

2022-04-26 01:24 UTC, epage requested changes
We will have everything pre-parsed by the regular parser, so we shouldn't need to error check this.

In my re-wording, I think some context was lost.  We need to error if the user sets any flags on the command-line that are incompatible with `workspace = true`.

2022-04-26 01:30 UTC, Muscraft commented
So the error should be during the parsing of the CLI flags?

2022-04-26 01:53 UTC, epage commented
> So the error should be during the parsing of the CLI flags?

It has to happen where we have access to the CLI flags and we know its a workspace dependency.  Note that we pass in a struct to the ops that basically represents the CLI, so we know the details.

Keep in mind that right now we are just loading an existing workspace entry.  We'll soon also take the name and look up to find if its a workspace dependency.

2022-04-26 02:04 UTC, Muscraft commented
Would it make sense to wait until after adding in where we take the name and look up to find if it's a workspace dependency, to do this?

2022-04-26 02:15 UTC, epage commented
We can implement the PRs in any order so long as we keep the work for both in mind though doing the other PR first will make this one more obvious for what to do

2022-04-26 02:20 UTC, Muscraft commented
I agree that one of the others would help make this slightly more clear. I'll do one of those and then come back to this.

2022-04-27 01:35 UTC, epage commented on tests/testsuite/cargo_add.rs
> +fn invalid_key_inherit_dependency() {
What about the case where the dependency already exists and we use one of these keys?

2022-04-27 01:35 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            let err_msg = "cannot be defined when inheriting a workspace dependency";
What if we rephrase this as
```
 "cannot override workspace dependency with `{}`, either change `workspace.dependencies.{}.{}` or define the dependency exclusively in the package's manifest"
```
- I feel like "defined" is confusing language in this context
- I feel like talking in terms of "overriding" is more specific and clear than generically talking about "inheriting"
- This provides a remediation

2022-04-27 01:35 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            }
> . This means you cannot define workspace with keys like version, registry, registry-index, path, git, branch, tag, rev, or package.

What about checking for
- path
- git
- version
- package

2022-04-27 01:43 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            }
The only package that is used here is to tell cargo add what package to add the dependency too. The others should be checked before this since they all would set a source from what I can tell

2022-04-27 01:46 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            let err_msg = "cannot be defined when inheriting a workspace dependency";
Does this override anything? To me, this only runs when it is not overriding something since it would've been found by `get_existing_dependency`. As for changing it I agree that we should change it to something else

2022-04-27 01:49 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            }
> The only package that is used here is to tell cargo add what package to add the dependency too.

Try a test case where you `cargo add --rename foo foo-alt` where `foo` is a workspace dependency and `foo-alt` is a workspace member.

> The others should be checked before this since they all would set a source from what I can tell

Thats right, we either do or will cover this with testing switching sources.  Probably good to add a comment about it.

2022-04-27 01:50 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            let err_msg = "cannot be defined when inheriting a workspace dependency";
I guess there are two different kinds of overriding to talk about.  This isn't writing over an existing fields value with a different one but it is instead overriding the field it inherits from `workspace.dependencies`.

2022-04-27 01:51 UTC, Muscraft commented on tests/testsuite/cargo_add.rs
> +fn invalid_key_inherit_dependency() {
I can add a test for this

2022-04-27 01:53 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            let err_msg = "cannot be defined when inheriting a workspace dependency";
Yeah, that makes sense. I'll change it to what you said

2022-04-27 02:03 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            }
> Try a test case where you `cargo add --rename foo foo-alt` where `foo` is a workspace dependency and `foo-alt` is a workspace member.

So `package` is `rename`? or at least that's the way it looks to me

> Thats right, we either do or will cover this with testing switching sources. Probably good to add a comment about it.

I'll add a comment about this

2022-04-27 02:15 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            }
I also do not know if we need branch, tag, or rev, since they can't be defined on their own

2022-04-27 12:10 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            }
I was thinking similar about branch, tag, and rev.

2022-04-27 12:19 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +        )
nit: this might read better if using the new format macro feature
```
            "cannot override workspace dependency with `{field}`, \
            either change `workspace.dependencies.{toml_key}.{field}` \
            or define the dependency exclusively in the package's manifest",
```

2022-04-27 12:19 UTC, epage commented on tests/snapshots/add/invalid_key_overwrite_inherit_dependency.in/primary/Cargo.toml
> +foo.workspace = true
Is this missing a `[dependencies]`?

2022-04-27 12:19 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +        anyhow::bail!("{}", err_msg(toml_key, "rename"))
This is a case where the argument and field diverge (`--rename` to cause `package` to be set)

In general, I feel like the error message will be easier to read with arguments
```
error: cannot override workspace dependency with `--rename`, either change `workspace.dependencies.foo.package` or define the dependency exclusively in the package's manifest
```

2022-04-27 12:19 UTC, epage commented on tests/testsuite/cargo_add.rs
> +        .args(["foo", "--registry", "registry", "-p", "bar"])
Is there a reason this test is using `--registry`?  I think it can obscure what you are trying to test by changing more variables.

2022-04-27 12:25 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +        anyhow::bail!("{}", err_msg(toml_key, "rename"))
```rust
fn err_msg(toml_key: &str, flag: &str, field: &str) -> String {
        format!(
            "cannot override workspace dependency with `{flag}`, \
            either change `workspace.dependencies.{toml_key}.{field}` \
            or define the dependency exclusively in the package's manifest"
        )
    }

    if arg.default_features.is_some() {
        anyhow::bail!("{}", err_msg(toml_key, "--default-features", "default-features"))
    }
    if arg.registry.is_some() {
        anyhow::bail!("{}", err_msg(toml_key, "--registry", "registry"))
    }
    // rename is `package`
    if arg.rename.is_some() {
        anyhow::bail!("{}", err_msg(toml_key, "--rename", "package"))
    }
```

2022-04-27 12:26 UTC, Muscraft commented on tests/snapshots/add/invalid_key_overwrite_inherit_dependency.in/primary/Cargo.toml
> +foo.workspace = true
It looks like it is

2022-04-27 12:26 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +        )
I'll change it to this

2022-04-27 12:27 UTC, Muscraft commented on tests/testsuite/cargo_add.rs
> +        .args(["foo", "--registry", "registry", "-p", "bar"])
There is no specific reason that used `--registry` here, do you think I should change it to `--default-features`?

2022-04-27 12:28 UTC, epage commented on tests/testsuite/cargo_add.rs
> +        .args(["foo", "--registry", "registry", "-p", "bar"])
Yes, please

2022-04-27 12:51 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            }
What if we combined the two and moved this to the end of the function?
- Check the source on `dependency` instead of `old_dep`
- Condition the check on the source being a Workspace

2022-04-27 12:53 UTC, epage reviewed
Once/if the checks get consolidated

2022-04-27 12:53 UTC, epage approved these changes
Ok, this time I remembered to actually approve

2022-04-27 12:54 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            }
That works for me. Does moving it to after `if dependency.source().is_none()`, instead of the end of the function work?

2022-04-27 13:14 UTC, epage commented on src/cargo/ops/cargo_add/mod.rs
> +            }
It doesn't have to be literally at the end of the function but among the clauses at the end of the function.

Stylistically, make sure it has newlines before and after since its not logically coupled to any of the blocks.

2022-04-27 13:15 UTC, Muscraft commented on src/cargo/ops/cargo_add/mod.rs
> +            }
That's how I have it! I'll push the changes and merge it then!

2022-04-27 15:34 UTC, merged